### ISSUE TITLE
現在のバージョン情報を表示したい

### ISSUE THREAD

**Issue by zeek0x** [TaneAkashi/DakokuApp#110]
ユーザーサポート時に役立つと思うので、どこかに表示したい。

表示場所の候補は、以下が考えられる

- 設定・ログイン画面
- トレイのアイテム
- 新しい画面

**Comment by amotarao** [comment]
<img width="396" alt="スクリーンショット 2021-06-04 8 15 07" src="https://user-images.githubusercontent.com/8909592/120723595-025f9f80-c50d-11eb-9039-18d9cda45f78.png">

**Comment by zeek0x** [comment]
む...↑はサンプルですか？それとももうこれを表示する方法がある？

**Comment by amotarao** [comment]
About App で見れます

**Comment by zeek0x** [comment]
Windows だとどうでしょう？

**Comment by amotarao** [comment]
おっとWindowsでは現状見れないですね。
ただSlackで同じ画面提供されてるので、用意したほうがいいかもですね

**Comment by zeek0x** [comment]
`About DakokuApp` のようなトレイアイテムを追加して、クリックで新しいページを開くようにしますか。

**Comment by amotarao** [comment]
VSCode
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/electron-sandbox/parts/dialogs/dialogHandler.ts#L158-L208

**Comment by amotarao** [comment]
Atom

そういう画面

![image](https://user-images.githubusercontent.com/8909592/122417360-60d45580-cfc4-11eb-9edc-b62e265f374f.png)

**Comment by zeek0x** [comment]
electron-about-window を使っている例
https://rhysd.hatenablog.com/entry/2016/12/11/191911
![img](https://cdn-ak.f.st-hatena.com/images/fotolife/r/rhysd/20161211/20161211191411.png)
