### ISSUE TITLE
Slackの投稿テストを追加する

### ISSUE THREAD

**Issue by zeek0x** [TaneAkashi/DakokuApp#118]
表題の通り

テスト方法を実装するにあたり、以下のことに注意する必要がある。

現状

- Akashiのログイン情報保存時にAkashiのログインテストが実行される。

そのため、操作の一貫性を考えると以下のようになると考えられる。

- 保存時に確認する方法
  - Akashi のログインテスト：ログイン情報保存時にログインテストをする（現在実装済）
  - Slack の投稿テスト：Slackの投稿情報保存時に投稿テストをする
- 保存後にテストボタンでテストする方法
  -  Akashi のログインテスト：Akashiログイン情報の保存ボタン横にテストボタンを設置し、ボタンが押されたらログインテストを実行する
  -  Slack の投稿テスト：Slackの投稿情報の保存ボタン横にテストボタンを設置し、ボタンが押されたら投稿テストを実行する

一貫性があるのであれば、他の案でもよい。

**Comment by zeek0x** [comment]
@amotarao ↑どちらがいいでしょうか？
別案でも構いません。

**Comment by amotarao** [comment]
保存時に確認したいです。
ただ、ログインテストは無害ですが、こちらはテスト投稿することを伝えたいので、

- 「保存」ボタンを「テスト投稿して保存」に変更
- 「Slack Incoming Webhook」の下に「保存時に投稿テストします」を挿入

のどちらかをしたいと思いました。文言は変えても大丈夫です。
ボタンのテキスト長くするのダサいので後者ですかねー。


またこのIssueと分けてもいいと思いますが、普段の操作でSlack投稿に失敗したら
失敗した通知を出してもよさそうですね。

**Comment by zeek0x** [comment]
#126

**Comment by zeek0x** [comment]
Slack投稿に失敗した場合には通知を出す issue を作成しました：#126
