### ISSUE TITLE
打刻 同時操作が片方失敗する

### ISSUE THREAD

**Issue by amotarao** [TaneAkashi/DakokuApp#28]
### 打刻終了を2回押したとき

<img width="351" alt="スクリーンショット 2021-04-10 20 38 56" src="https://user-images.githubusercontent.com/8909592/114268588-c93f0d80-9a3c-11eb-872d-02ff79cbfd68.png">

### その2

<img width="676" alt="スクリーンショット 2021-04-10 20 39 22" src="https://user-images.githubusercontent.com/8909592/114268605-dc51dd80-9a3c-11eb-93c4-217a73302427.png">

**Comment by amotarao** [comment]
打刻を無効にする

```js
const enableMenuItems = () => {
  contextMenu.items.forEach(item => item.enabled = true);
}
const disableMenuItems = () => {
  contextMenu.items.forEach(item => item.enabled = false);
}
```

**Comment by amotarao** [comment]
同時操作は無効にしたほうがよさそう

別に、
同時操作してしまった場合にブラウザの挙動がおかしいのを修正する

**Comment by zeek0x** [comment]
どの行でエラー出てるってわかりましたっけ？
できればスタックトレースも欲しいです。

**Comment by amotarao** [comment]
30000ms のエラーなので akashi-dakoku-core の Puppeteer 処理が途中で止まってる感じかなと思います

行で言うと https://github.com/TaneAkashi/DakokuApp/pull/30/files#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dR68-R69 ここですかね
