### ISSUE TITLE
起動直後の打刻に失敗する

### ISSUE THREAD

**Issue by amotarao** [TaneAkashi/DakokuApp#29]
<img width="358" alt="スクリーンショット 2021-04-10 20 47 07" src="https://user-images.githubusercontent.com/8909592/114268792-f93ae080-9a3d-11eb-8b8b-4581b28937c3.png">

**Comment by amotarao** [comment]
初期化が済んでなさそう

**Comment by zeek0x** [comment]
他のエラー

<img width="185" alt="スクリーンショット 2021-04-12 1 41 45" src="https://user-images.githubusercontent.com/12657833/114313144-426b5d00-9b30-11eb-81fe-6446783c1764.png">

適切な enalbe / disable の状態管理が必要
#28 の修正込みでやると良さそう

**Comment by amotarao** [comment]
TS化のときついでにError吐くようにしたのでエラーの内容は同じですね
