### ISSUE TITLE
設定画面でスクロールが発生する

### ISSUE THREAD

**Issue by amotarao** [TaneAkashi/DakokuApp#9]

**Comment by zeek0x** [comment]
閉じるボタンがいらないかも

**Comment by amotarao** [comment]
ウィンドウの閉じるを使わせたくなかった理由があったが、根本的に解決させれば問題なさそう
「❌でアプリ自体が終了してしまう」 を防止

**Comment by amotarao** [comment]
いやしななかった。なぜ閉じるボタンおいたのか忘れた。とってしまおう。

**Comment by zeek0x** [comment]
@amotarao そんなに問題になってないので閉じていいかもしれません。

**Comment by amotarao** [comment]
問題というか気にしない人がほとんどだと思うのでcloseします
