### ISSUE TITLE
アップデート案内が毎打刻時に出る

### ISSUE THREAD

**Issue by amotarao** [TaneAkashi/DakokuApp#92]
1回だけじゃなさそう

**Comment by zeek0x** [comment]
`notification` は１回のみにすべきですか？

**Comment by amotarao** [comment]
過剰な通知はユーザーに不快感を与えると思います。
トレイに残るので、1回のみでいいと思います。

**Comment by zeek0x** [comment]
管理めんどくさいですし、やっぱり`notification`なくても良さそうな...？

**Comment by zeek0x** [comment]
通知は、一度きりでしょうか？（アプリ再起動時には再通知したりしないですか？）
